#+LATEX_CLASS: article
#+TITLE: vcsh: Git workflow, practices, and automation
#+AUTHOR: Mr. Mattie

* Introduction

In many cases developers huddled around their limited knowledge of
tools, like a swimmer clinging to a life vest. Instead of enabling
progress with tools, the tools were the issue, day in and day out.

Starting in 2020 I tried to sort out this mess with automation. It
started as a Makefile, then a bash script called manage.sh, and
finally PythonSh. 

The idea was to build correct tool use into a single command, with
intelligence to tailor it to a context and scenario.

I had built tooling into a PythonSH workflow tool. After I had made
general tooling, version control, and python dev management I realized
I had built a monolith.

I decided that I needed to break out the Version Control workflow into
Git only tooling.

* VCsh

VCsh is a DWIM tool for using itegration trunk, and github fork/pull
models together to make it easy and reliable to use git effectively.

In scope was operations that require multiple git commands, bundling
them into a single task command. Also error prone commands are
enhanced by dry run mode which shows the commands without executing
them.

Out of scope is simple commands that would result in a trivial
wrapper, like the git "stash" commands which are so simple a basic
shell alias is sufficient.

Most of the GitHub fork style commands dont need wrapping because
they are too simple. Documenting how to make use of Trunk/GitHub style
workflows is enough to use effectively.

* MalPractices

Often times developers get crowded into a single monolothic repository
because the construction of a new repo and it's devops toolchain is
magical, and laborious.

They collide frequently leading developers to "section off" their
files and avoid merging. When the inevitable merge occurs at release
build time there is a frantic late-night integration sessions and
working Saturdays to get the build done by Monday.

* Better Practices

A better approach is to use the Atlassian GitFlow [[cite:&flow]] workflow
with a integration trunk and feature branches. This model encourages
frequent merging so the trees do not diverge.

This model alone is quite usable, however the GitHub model has it's
advantages as well. In the GitHub model the developer clones the repo
into their own sandbox. When they are ready the lead pulls their work
into the master repo.

This model is different in technique, but similar to the integration
trunk in that it creates a sandbox for the developer to work in.
Frequent merging is relatively straight forward.

A common pattern in development is for a couple or more developers to
work together on some code, and try and stay in sync with each other,
and with the project generally.

This can become complicated, and result into fear and loathing of
merging.

A good solution IMHO is to use a hybrid of both approaches. Maintain
a trunk model centralized repository, and use the integration trunk
for project scope integration.

Feature branches in the centralized repository are used for small
groups to sychronize. The small teams push/pull on the feature
branches, which are then merged in the master repo by the lead when
the work is completed.

"beta" tags use automatic version incrementing to provide conveinant
team wide synchronization.

The team integrates on the trunk, feature branches support one or
more workers working together, and branches and repositories are
disposable.

Disposable branches and repos are critical since git repositories are
really easy to damage.

* Shell Customizations

Before diving into the workflow, there are some small commands
to review first.

I have some shell customizations that I use that some might
want to use. I extensively customize Zsh with a decent set
of commands ad aliases that are git specific, and some that
are general purpose.

The prompt is usefull generally in that it shows the branch,
wether the work area is dirty, and the python environment
activated.

#+BEGIN_SRC bash
vc tools-zshrc
vc tools-custom
vc tools-prompt
#+END_SRC

#+BEGIN_SRC bash
<work> [system] pythonsh:develop(*+) ->
#+END_SRC

- work is the system name so you dont get confused when remoting into other systems
- system is the virtualenv which is not activated in this case.
- pythonsh is the repository you are at.
- develop is the current branch
- () encloses * and + , where * = dirty, and + = staged changes

** Conventional Commits and Reports

Conventional commits [[cite:&conventional]] is a standard for semantics
and formatting of commits. I use it as a starting point, and add a
couple such as refactor, and sync.

#+BEGIN_SRC bash
(feat) add a new dialog for listing reports
#+END_SRC

These conventions are crucial since it makes it clear to developers
what a commit consists of, and allows tools to process the history in
powerful ways.

To really understand the power of conventional commits you have
to consider the tooling. What if it was possible to generate
release notes entirely from commits ? Pythonsh does!

This is what a history looks like, a jungle of different types of commits:

#+BEGIN_SRC bash
(sync) [2024-03-16T08:16:03-07:00] syncd: pythonsh
04fb73e Merge branch 'release/0.10.0' into develop
8f13b6b (sync) [2024-03-15T22:35:36-07:00] syncd: pythonsh
776971e (release) release 0.10.0 many fixes to dwim, support for org mode etc..
dbd926b (fix) insert the commit type as well as the message and report
1ad304d (fix) report no longer takes a message argument so insert the message ourselves
c6f8a67 (sync) [2024-03-15T22:14:20-07:00] syncd: pythonsh
0fbf0df (feat) create a insert-syncd command that generates a sync commit message
fd93322 (sync) 3-15-2024 sync pythonsh
b8b069a (fix) make m keybinding be menu and remove a
420f003 (feat) functionalize the helm frame configuration
7bea9b9 (sync) 3-15-2024 sync latest citeproc,helm, and helm-bibtext
ec46225 (fix) add ignore=dirty to helm-frame
#+END_SRC

This is what a report looks like. It groups the commits by type and
is injectable into a commit. This allows for editing the report
into release notes in the commit.

Without release notes it's only tribal knowledge what is in a release
or not. Professionals do not leave history up to word of mouth. Take
a look at a report and see how easy it is to edit into release notes.

#+BEGIN_SRC bash
devil> [system] grail:develop(*) -> ./py.sh status-report

,* features

(feat) through questions determine what type of report to insert
(feat) create a insert-syncd command that generates a sync commit message
(feat) show the branch on the modeline
(feat) add a bunch of fonts and a install script for macos
(feat) add a tramp command that opens dired on the host home directory
(feat) revamp the scripts to build emacs from brew and deal with byte copmilation

,* fixes

(fix) insert the commit type as well as the message and report
(fix) report no longer takes a message argument so insert the message ourselves
(fix) make m keybinding be menu and remove a
(fix) add ignore=dirty to helm-frame
(fix) fix the battery with a closing >
(fix) remove initial bib file which is obsoleted by compsci repo now
(fix) disable helm-frame for now

,* syncs

(sync) [2024-03-16T08:16:03-07:00] syncd: pythonsh
(sync) [2024-03-15T22:35:36-07:00] syncd: pythonsh
(sync) [2024-03-15T22:14:20-07:00] syncd: pythonsh
(sync) 3-15-2024 sync latest citeproc,helm, and helm-bibtext
(sync) ff pythonsh to 3-15-2024
(sync) sync helm core 3-15-2024

,* refactor

(refactor) clean up formatting so it's easier to read
(refactor) cleanup formatting
(refactor) pull all the scripts and files for emacs from pythonsh and combine into compile-emacs.sh
(refactor) minor whitespace changes
(refactor) clean up lex-cache and check dwim-complete
<devil> [system] grail:develop(*) ->
#+END_SRC

Here are my prefixes which extend the conventional commit standard:

- (feat) new features. A oneliner is either sufficient or some prose is added below
  the main commit line.
- (fix) this is primarily for development. They belong on feature branches.
  fixes are corrections to code that has not been released yet.
- (merge) feature merges into trunk
  included in the release notes
- (sync) a fast-forward. This is done only on the trunks: develop and main where they
  are histories that are stable, and consist entirely of merges.
- (refactor) releases are alpha and beta releases. The actual release process with
  git flow release start is more complex and is documented below

This systematic annotating of the history makes it possible to
understand the changes far beyond cryptic and poor commit messsages.

This also allows for tools that help insert commit messages, and
generate entire release notes into merge commits and the like.

* Integration Model

git flow init and the developer work by this process:

- developer: works in "feature" branch and merges develop changes from
  the trunk

- lead: when a feature is done it is merged back into "develop"

- lead: when integration is complete a "release" merges develop into
  "main".

** PythonSh Version Control Feature Summary

- info = show branches, tracking, and status
- verify = verify commit cryptographic signatures
- status = show status of repository and all sub-modules
- pull = pull current branch no ff
- history = show commit history
- summary = show diffstat between feature and develop or last release and develop
- ahead = show log of commits in branch but not in parent
- behind = show log of commit in parent but not branch

- report = 
- graph = show history between feature and develop or last release and develop

** PythonSh Version Control in-depth

Let's look at the version control capabilities in-depth and see what
developers could do if they intensively studied git and git-flow.

*** status

This is a example of using status:

#+BEGIN_SRC bash
<devil> [pastepipe_dev] pastepipe:develop(*) -> status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  modified:   Pipfile.lock
  modified:   pyproject.toml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
  dist/
  src/pastepipe.egg-info/

no changes added to commit (use "git add" and/or "git commit -a")
<devil> [pastepipe_dev] pastepipe:develop(*) ->
#+END_SRC

*** info

#+BEGIN_SRC bash
<mobile> [system] pythonsh:develop(*) -> ./py.sh info
,* develop 879b2a4 [origin/develop] (feat): put code directory [zshrc.custom]
  main    7f47e7c [origin/main: behind 134] Merge branch 'release/0.15.1'
[staged]
 0 files changed
[changes]
 pythonsh.org |  130 ++++++++++++++++++++++++++++++++++-------------------------
 1 file changed, 75 insertions(+), 55 deletions(-)
[untracked]
<mobile> [system] pythonsh:develop(*) ->
#+END_SRC

py.sh info shows the stauts of the branches and the repo. this is a
very handy command.

*** track

- track <1> <2>  = set upstream tracking 1=remote 2=branch

sometimes you need to set the upstream for a branch. track makes this
easy.

*** fetch & pull

- fetch = fetch main, develop, and current branch
- pull  = pull to current branch no ff

fetch retrieves the commits from upstream but does not merge
them. pull is basically fetch + merge.

*** staged

- staged     = show staged changes

show staged changes. Note that git diff
showing the unstaged changes is a shell alias.

*** Advanced View

- merges = show merges only
- history = show commit history
- summary = show diffstat of branch to trunk or trunk to release.
- delta = show diff of branch to trunk or trunk to release
- log = show log of branch to trunk or trunk to release
- graph = show history graph of branch to trunk or trunk to release
- upstream = show upstream changes that havent been merged yet

The most powerful feature is "agains the parent". What this means is
that pythonsh detects if it's on a feature branch, the develop trunk,
or the main trunk.

- if on a feature branch it's a diff from develop -> feature
- if on the develop branch it's a diff from main -> develop
- if on main it's a diff from the last tag -> main

This intelligence means a single command can be used in three
different contexts with no additional arguments.

- sync = merge from the root branch commits not in this branch no ff

sync is a tool to pull changes from the parent into the current branch. This
is used for when development work on the develop trunk needs to be merged
into the feature branch.

*** tagging

- tag-beta = <feat> <msg> : create a beta tag on the trunk

tagging is important for making a file set for alpha or beta
releases. by drawing a line across the repository the entire state of
the repo can be checked out.

* Appendix

#+print_bibliography:
